# Generated by Django 3.2.10 on 2021-12-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('T', 'Twitter'), ('R', 'Reddit'), ('G', 'Google'), ('Q', 'Quaora')], max_length=1)),
                ('user', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('id', 'platform')},
            },
        ),
    ]
